### ISSUE TITLE
geolocation not found

### ISSUE THREAD

**Issue by acopernic** [Super-Visions/sv-geolocation#3]
Hi,
I've installed your plugin (itop 2.7.x). It's installed and the "geolocation" appears in the dashboard but I cannot edit, add, modify or even see the field "geolocation" in the Location page.
Any idea how to solve this.
I figure it may be a problem with other plugins (jb-tweak for config-mgmt and or Molkobain).
Thanks

**Comment by Hipska** [comment]
Hi, could you provide me the Support information (Power button > About iTop… > Support information) and paste this in this ticket between code blocks: ```
Then we can have a look which modules might be conflicting..

**Comment by acopernic** [comment]
Hi,

Here the ticket:

===== begin =====
iTopVersion: 2.7.7
iTopBuild: 9622
iTopBuildDate: 2022-07-12 16:06:00
DataModelVersion: 2.7.7
MySQLVersion: 8.0.31
PHPVersion: 7.4.30
OSVersion: Linux
WebServerVersion: Apache/2.4.54 (Debian)
PHPModules: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mcrypt, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
ItopSetting/cron_max_execution_time: 600
ItopSetting/timezone: Europe/Paris
PHPSetting/memory_limit: 128M
PHPSetting/max_execution_time: 30
PHPSetting/upload_max_filesize: 10M
PHPSetting/post_max_size: 12M
MySQLSetting/max_allowed_packet: 67108864
MySQLSetting/key_buffer_size: 8388608
MySQLSetting/query_cache_size:
MySQLStatus/Key_read_requests: 0
MySQLStatus/Key_reads: 0
InstallDate: 2022-10-25 21:51:44
InstallPath: /var/www/html/itop-dev/
---- Installation choices ----
InstalledExtension/itop-config-mgmt-core/2.7.7
InstalledExtension/itop-config-mgmt-datacenter/2.7.7
InstalledExtension/itop-config-mgmt-end-user/2.7.7
InstalledExtension/itop-config-mgmt-storage/2.7.7
InstalledExtension/itop-config-mgmt-virtualization/2.7.7
InstalledExtension/itop-service-mgmt-service-provider/2.7.7
InstalledExtension/itop-ticket-mgmt-itil-user-request/2.7.7
InstalledExtension/itop-ticket-mgmt-itil-incident/2.7.7
InstalledExtension/itop-ticket-mgmt-itil-enhanced-portal/2.7.7
InstalledExtension/itop-ticket-mgmt-itil/2.7.7
InstalledExtension/itop-change-mgmt-itil/2.7.7
InstalledExtension/itop-kown-error-mgmt/2.7.7
InstalledExtension/itop-problem-mgmt/2.7.7
InstalledExtension/triangle-passive/1.0.0 (Extension)
InstalledExtension/triangle-bts/1.0.0 (Extension)
InstalledExtension/triangle-look/1.0.1 (Extension)
InstalledExtension/triangle-document-location/1.0.0 (Extension)
InstalledExtension/jd-class-locks/2.4.180309 (Extension)
InstalledExtension/jd-profiles-technicalservices/2.4.180309 (Extension)
InstalledExtension/jd-class-document-subtypes/2.4.180418 (Extension)
InstalledExtension/jd-class-tools/2.4.180309 (Extension)
InstalledExtension/molkobain-datacenter-view/1.9.0 (Extension)
InstalledExtension/molkobain-fontawesome5-pack/1.4.0 (Extension)
InstalledExtension/molkobain-newsroom-provider/1.1.0 (Extension)
InstalledExtension/molkobain-caselogs-toggler/1.6.0 (Extension)
InstalledExtension/molkobain-datacenter-view-extended-bridge-for-teemip/1.5.0 (Extension)
InstalledExtension/molkobain-bubble-caselogs/1.5.0 (Extension)
InstalledExtension/molkobain-console-tooltips/1.1.2 (Extension)
InstalledExtension/molkobain-markdown-viewer/1.3.0 (Extension)
InstalledExtension/molkobain-datacenter-view-extended/1.7.1 (Extension)
InstalledExtension/sv-auto-dispatch/1.1.0 (Extension)
InstalledExtension/sv-geolocation/1.7.0 (Extension)
InstalledExtension/itop-currency-list/0.0.1 (Extension)
InstalledExtension/combodo-dispatch-userrequest/1.1.11 (Extension)
InstalledExtension/molkobain-portal-mosaic-service-catalog/1.0.0 (Extension)
InstalledExtension/combodo-dispatch-incident/1.1.9 (Extension)
InstalledExtension/jb-tweaks-config-mgmt/2.6.200805 (Extension)
InstalledExtension/jb-lnkconnectablecitoconnectableci/2.6.210802 (Extension)
InstalledExtension/jb-tweaks-teemip/2.6.200805 (Extension)
InstalledExtension/jb-tweaks-request-mgmt-itil/2.6.200805 (Extension)
InstalledExtension/jb-networkdevices/2.6.210826 (Extension)
InstalledExtension/jb-ipdevices-main/2.6.200409 (Extension)
InstalledExtension/jb-tweaks-incident-mgmt-itil/2.6.200805 (Extension)
InstalledExtension/combodo-location-hierarchy/1.0.1 (iTop Hub)
InstalledExtension/teemip-core-ip-mgmt/3.0.0 (iTop Hub)
InstalledExtension/combodo-workflow-graphical-view/1.1.0 (iTop Hub)
InstalledExtension/itop-iframe-dashlet/1.1.0 (iTop Hub)
InstalledExtension/combodo-webhook-integration/1.1.1 (iTop Hub)
InstalledExtension/teemip-network-mgmt-extended/3.0.0 (iTop Hub)
---- Actual modules installed ----
InstalledModule/authent-cas: 2.7.7
InstalledModule/authent-external: 2.7.7
InstalledModule/authent-ldap: 2.7.7
InstalledModule/authent-local: 2.7.7
InstalledModule/combodo-db-tools: 2.7.7
InstalledModule/combodo-workflow-graphical-view: 1.1.0
InstalledModule/itop-attachments: 2.7.7
InstalledModule/itop-backup: 2.7.7
InstalledModule/itop-config-mgmt: 2.7.7
InstalledModule/itop-config: 2.7.7
InstalledModule/itop-datacenter-mgmt: 2.7.7
InstalledModule/itop-endusers-devices: 2.7.7
InstalledModule/itop-files-information: 2.7.7
InstalledModule/itop-hub-connector: 2.7.7
InstalledModule/itop-iframe-dashlet: 1.1.0
InstalledModule/itop-portal-base: 2.7.7
InstalledModule/itop-portal: 2.7.7
InstalledModule/itop-profiles-itil: 2.7.7
InstalledModule/itop-sla-computation: 2.7.7
InstalledModule/itop-storage-mgmt: 2.7.7
InstalledModule/itop-tickets: 2.7.7
InstalledModule/itop-virtualization-mgmt: 2.7.7
InstalledModule/itop-welcome-itil: 2.7.7
InstalledModule/jb-lnkconnectablecitoconnectableci: 2.6.210802
InstalledModule/jb-networkdevices: 2.6.210826
InstalledModule/jb-tweaks-config-mgmt: 2.6.200805
InstalledModule/jd-class-document-subtypes: 1.0.0
InstalledModule/jd-class-locks: 2.4.180824
InstalledModule/jd-class-tools: 2.4.180215
InstalledModule/molkobain-fontawesome5-pack: 1.4.0
InstalledModule/molkobain-handy-framework: 1.8.0
InstalledModule/molkobain-newsroom-provider: 1.5.0
InstalledModule/molkobain-portal-mosaic-service-catalog: 1.0.0
InstalledModule/sv-geolocation: 1.7.0
InstalledModule/teemip-framework: 3.0.0
InstalledModule/teemip-network-mgmt: 3.0.0
InstalledModule/triangle-document-location: 1.0.0
InstalledModule/triangle-look: 1.0.0
InstalledModule/combodo-location-hierarchy: 1.0.1
InstalledModule/combodo-webhook-integration: 1.1.1
InstalledModule/itop-bridge-virtualization-storage: 2.7.7
InstalledModule/itop-change-mgmt-itil: 2.7.7
InstalledModule/itop-core-update: 2.7.7
InstalledModule/itop-incident-mgmt-itil: 2.7.7
InstalledModule/itop-knownerror-mgmt: 2.7.7
InstalledModule/itop-oauth-client: 2.7.7
InstalledModule/itop-problem-mgmt: 2.7.7
InstalledModule/itop-request-mgmt-itil: 2.7.7
InstalledModule/itop-service-mgmt-provider: 2.7.7
InstalledModule/jb-ipdevices-main: 2.6.200409
InstalledModule/jb-tweaks-incident-mgmt-itil: 2.6.200805
InstalledModule/jb-tweaks-request-mgmt-itil: 2.6.200805
InstalledModule/jd-profiles-technicalservices: 1.0.0
InstalledModule/molkobain-bubble-caselogs: 1.5.0
InstalledModule/molkobain-caselogs-toggler: 1.6.0
InstalledModule/molkobain-console-tooltips: 1.3.0
InstalledModule/molkobain-datacenter-view: 1.10.1
InstalledModule/molkobain-markdown-viewer: 1.3.0
InstalledModule/teemip-ip-mgmt: 3.0.0
InstalledModule/teemip-ipv6-mgmt: 3.0.0
InstalledModule/teemip-newsroom-provider: 1.1.1
InstalledModule/teemip-webservices: 3.0.0
InstalledModule/triangle-passive: 1.0.0
InstalledModule/combodo-dispatch-incident: 1.1.9
InstalledModule/combodo-dispatch-userrequest: 1.1.11
InstalledModule/itop-currency-list: 1.0.0
InstalledModule/itop-full-itil: 2.7.7
InstalledModule/jb-ipdevices-lnkconnectablecitoconnectableci: 2.6.200409
InstalledModule/molkobain-datacenter-view-extended: 1.7.1
InstalledModule/sv-auto-dispatch: 1.1.0
InstalledModule/teemip-config-mgmt-adaptor: 3.0.0
InstalledModule/teemip-datacenter-mgmt-adaptor: 3.0.0
InstalledModule/teemip-endusers-devices-adaptor: 3.0.0
InstalledModule/teemip-network-mgmt-extended: 3.0.0
InstalledModule/teemip-storage-mgmt-adaptor: 3.0.0
InstalledModule/teemip-virtualization-mgmt-adaptor: 3.0.0
InstalledModule/triangle-bts: 1.0.0
InstalledModule/jb-ipdevices-teemip: 2.6.200409
InstalledModule/jb-tweaks-teemip: 2.6.200805
InstalledModule/molkobain-datacenter-view-extended-bridge-for-teemip: 1.5.0
InstalledModule/teemip-bridge-virtualization-network-extended: 1.1.0
===== end =====

Thanks.
________________________________

**Comment by Hipska** [comment]
Thanks, can you also figure out which of these modify the `Location` class? I believe one of them is redefining the presentation.

**Comment by acopernic** [comment]
I will check

Oct 26, 2022 18:30:24 Thomas Casteleyn ***@***.***>:

**Comment by Hipska** [comment]
Never mind, I found out it is because of “Location hierarchy”. I’ll try to make the module compatible.

**Comment by acopernic** [comment]
Oh. Thanks.

Oct 26, 2022 20:22:20 Thomas Casteleyn ***@***.***>:

**Comment by Hipska** [comment]
I checked and it seems not (easily) possible to be compatible with default datamodel Location and also with Location Hierarchy extension..

What you can do is with your own extension, re-add the `geo` field on the presentation in the place you like.

There will be a future release which will add the field in the presentation of Location Hierarcy, but it will not be in one of the field sets..

**Comment by acopernic** [comment]
Hi,

Understood. I will do this.
Thanks for the support.

Regards.

Oct 27, 2022 13:09:57 Thomas Casteleyn ***@***.***>:

**Comment by Hipska** [comment]
Release 1.8.0 is out 😉

**Comment by acopernic** [comment]
Thanks

Oct 28, 2022 09:41:22 Thomas Casteleyn ***@***.***>:

**Comment by acopernic** [comment]
Working..

Just one thing about openstreetmap .. We have this (for a while now). Working with Mapquest and GoogleMaps but with openstreetmap as I saw they change and the "mapping" does not work anymore. Will move to Leaflet someday.
[cid:17ba492a-a022-4ffd-9d06-3632d8ae76ca]
________________________________

**Comment by Hipska** [comment]
Yes this is a wanted feature as well, see #2. PRs are welcome!
